fix: exclude pg_toast when querying triggers
In cloud we need to exclude `pg_toast` from the query that checks if the
invalidation trigger exists, otherwise we get:

```
2023-07-24T20:19:40.048599Z DEBUG src/execute.rs:126: Attempting to drop
invalidation trigger on '"_timescaledb_internal"."_hyper_27_1458_chunk"'

Error: worker pool error

Caused by:
    0: worker execution error
    1: db error: ERROR: permission denied for schema pg_toast
    2: ERROR: permission denied for schema pg_toast
```